// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxrj5s-u92L80L_5E_8hiNVvCnohQm4pM',
    appId: '1:991898101582:web:c242582cfcf85008e0a01f',
    messagingSenderId: '991898101582',
    projectId: 'notes-18fb6',
    authDomain: 'notes-18fb6.firebaseapp.com',
    storageBucket: 'notes-18fb6.firebasestorage.app',
    measurementId: 'G-EZMHP40TVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCreuU7YQwMmIpYQBI5F-W69NLmNXRPxGM',
    appId: '1:991898101582:android:8a4c272bd447195ae0a01f',
    messagingSenderId: '991898101582',
    projectId: 'notes-18fb6',
    storageBucket: 'notes-18fb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcX-96ZINkCeUazNYjl-DOByFdClWAgB4',
    appId: '1:991898101582:ios:8ec598d7c79950bde0a01f',
    messagingSenderId: '991898101582',
    projectId: 'notes-18fb6',
    storageBucket: 'notes-18fb6.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
